import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  compileDigest,
  loadSignalsFromArchive,
  renderDigestHtml,
  writeDigestFiles,
  type DigestSignal,
} from "../src/index.js";
import type { LlmClient, LlmRequest } from "@polis/runtime";

function tempDir(): { dir: string; cleanup: () => void } {
  const dir = mkdtempSync(join(tmpdir(), "polis-newsletter-test-"));
  return { dir, cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

function writeJson(path: string, value: unknown): void {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function signal(overrides: Partial<DigestSignal> = {}): DigestSignal {
  return {
    v: 1,
    kind: "post",
    topic: "town.general",
    from: "abcdef1234567890",
    content: "Gensyn AXL batched receipts landed with verifier caveats.",
    ts: 1_700_000_000_000,
    id: "sig-1",
    ...overrides,
  };
}

test("loadSignalsFromArchive reads TownMessages, filters by topic, and sorts", () => {
  const { dir, cleanup } = tempDir();
  try {
    writeJson(join(dir, "b.json"), signal({ id: "b", ts: 200, topic: "town.general" }));
    writeJson(join(dir, "a.json"), signal({ id: "a", ts: 100, topic: "town.general" }));
    writeJson(join(dir, "ignored.json"), signal({ id: "ignored", topic: "other" }));
    writeJson(join(dir, "not-message.json"), { hello: "world" });

    const signals = loadSignalsFromArchive(dir, { topic: "town.general" });

    assert.deepEqual(signals.map((item) => item.id), ["a", "b"]);
    assert.equal(signals[0]?.archivePath, join(dir, "a.json"));
  } finally {
    cleanup();
  }
});

test("compileDigest asks the reviewer LLM and renders artifacts", async () => {
  const calls: LlmRequest[] = [];
  const llm: LlmClient = {
    provider: "groq",
    defaultModel: "test-model",
    complete: async (req) => {
      calls.push(req);
      return {
        text: [
          "# Open Agents Daily",
          "",
          "## TL;DR",
          "- Agents found a real AXL integration risk.",
          "",
          "## Credits",
          "- abcdef1234...",
        ].join("\n"),
        usage: { inputTokens: 10, outputTokens: 20 },
      };
    },
  };

  const digest = await compileDigest({
    llm,
    signals: [signal()],
    generatedAt: new Date("2026-04-25T00:00:00.000Z"),
  });

  assert.equal(calls.length, 1);
  assert.match(calls[0]!.userMessage, /Archived agent signals/);
  assert.equal(digest.title, "Open Agents Daily");
  assert.equal(digest.subject, "Open Agents Daily");
  assert.equal(digest.signalCount, 1);
  assert.match(digest.html, /<h1>Open Agents Daily<\/h1>/);
  assert.match(digest.text, /Generated by Polis reviewer-agent/);
});

test("renderDigestHtml escapes agent content", () => {
  const html = renderDigestHtml({
    id: "digest",
    signalCount: 1,
    signals: [],
    markdown: "# Hi\n\n<script>alert('x')</script>",
  });

  assert.match(html, /&lt;script&gt;alert\(&#39;x&#39;\)&lt;\/script&gt;/);
  assert.doesNotMatch(html, /<script>/);
});

test("writeDigestFiles creates markdown, html, and json outputs", async () => {
  const { dir, cleanup } = tempDir();
  try {
    const llm: LlmClient = {
      provider: "groq",
      defaultModel: "test-model",
      complete: async () => ({ text: "# Digest\n\n## TL;DR\n- one" }),
    };
    const digest = await compileDigest({
      llm,
      signals: [signal()],
      generatedAt: new Date("2026-04-25T00:00:00.000Z"),
    });

    const paths = writeDigestFiles(digest, { outDir: dir });

    assert.match(paths.markdown, /\.md$/);
    assert.match(paths.html, /\.html$/);
    assert.match(paths.json, /\.json$/);
  } finally {
    cleanup();
  }
});
